npm/make-fetch-happen

- cache.js
Changes condition/logic of `fitInMemory` used when defining `memoize`
> fix: broken `memoize` logic @ v6

- index.js
- test/exports.js
If this package is a super set of `node-fetch` (well `minipass-fetch`) it should share the same exports. Furthermore, trying to test this package against `node-fetch` classes fails because it is obscure that this uses a fork of that module.
> fix: Keep exports the same as `node-fetch`

- lib/cache/policy.js
- test/cache.js
when the npm CLI self updates itself, it retires its own directory
before attempting to extract the new archive. negotiator happens to
use lazy loading and only requires its modules when they're needed
so we have to call methods that trigger the lazy loading as soon as
we can to make sure they're in memory before the npm CLI retires
its own directory
> fix: force negotiator to preload all modules

- lib/cache/entry.js
- lib/cache/index.js
- test/cache.js
- test/integrity.js
these changes align our cache modes with the whatwg fetch spec.
previously, 'reload' was behaving how 'no-cache' is meant to and
'no-cache' wasn't implemented at all
related to npm/cli#3424
> fix: implement cache modes correctly

- lib/remote.js
this is the equivalent of an ETIMEDOUT from node core, but is the error code that agentkeepalive surfaces when it destroys a socket due to an idle timeout. this is definitely something we should retry.
> fix: retry ERR_SOCKET_TIMEOUT from agentkeepalive

- lib/cache/entry.js
- test/cache.js
pacote has a feature where if it fails to read content from cacache for whatever reason, it removes the content by its integrity value and retries the request. when this happens, make-fetch-happen was finding the still present and still valid index and attempting to respond with the content that was just deleted, yielding an ENOENT. this patch makes it so when an ENOENT is encountered reading content from cacache, we delete the index for the request before we raise the error back out to the user. this way if the user retries the request, they'll actually stand a chance of getting a response instead of us just raising the same ENOENT over and over.
i've also made it so an EINTEGRITY error will remove the content and the index for the same purposes. pacote does the removal of the content …
> fix: when encountering errors reading content, clean up after ourselves

- lib/cache/entry.js
- lib/cache/policy.js
this is to avoid cacache.verify() overwriting the entry's timestamp and causing make-fetch-happen to believe every index is fresh
closes #55
> fix: store a timestamp in the metadata instead of relying on the entry

- lib/agent.js
- lib/options.js
- test/agent.js
- test/lambda-agent.js
- test/options.js
when calculating the agent cache key, use the same coercion of the strictSSL option to default as tls.connect’s rejectUnauthorized so that we don’t use a cached agent that is inconsistent with the behavior when creating a new agent.
I was reading the source to find the default behavior of `strictSSL` and I discovered that `tls.connect` uses the value `rejectUnauthorized !== false`, but `getAgent` creates a cache key containing `!!strictSSL` instead. That means that if you call `fetch('https://example.com/', {strictSSL: false})` followed by `fetch('https://example.com/', {})`, the second call would not verify the TLS certificate even though it should!
Also, `configureOptions` was setting `options.rejectUnauthorized`, but this wasn’t used by `getAgent`.
This commit coerces `useSSL` to …
> fix: use the same strictSSL default as tls.connect

- lib/fetch.js
- test/fetch.js
Fixes https://github.com/npm/make-fetch-happen/issues/70
> fix: strip cookie header on redirect across hostnames

- lib/cache/policy.js
- package.json
- test/cache.js
- deps: negotiator@0.6.3
- fix: revert negotiator preload hack
- deps: npmlog@6.0.0
- deps: http-proxy-agent@5.0.0
> update deps, roll back lazy load hack'

- lib/agent.js
- test/agent.js
this is a bit of a bandaid for the timeout issue that got introduced here recently. it makes our tests pass consistently again without timeouts, but it does also indicate some potential issues in minipass-fetch. or at least issues between minipass-fetch and agentkeepalive..
either way, this would be great to land to get our CI happy again and to stop causing other peoples tests to potentially fail (node-gyp saw this issue on their end as well) and we can move on to figuring out how to fix the root cause later.
> fix: set agentkeepalive freeSocketTimeout back to 15 seconds

- README.md
- lib/agent.js
- lib/dns.js
- lib/options.js
- test/agent.js
- test/dns.js
- test/options.js
> feat: implement local dns cache

- lib/dns.js
defaulting `verbatim` to `undefined` allows both the node flag `--dns-result-order` and `dns.setDefaultResultOrder()` to be respected
closes #134
> fix: default verbatim to undefined

- lib/index.js
- test/defaults.js
The README says:
> A defaulted `fetch` will also have a `.defaults()` method, so they can
> be chained.
But this didn't really work, because while the `defaults` method was
placed on the `defaulted` fetch, a chained defaulted fetch would just
call the original fetch function directly instead of the intermediate
function.
This PR makes chaining actually work and adds a test.
Also, it fixes the previous test, which wasn't actually verifying that
the correct request headers were received because it used the nock API
incorrectly: the option is `reqheaders` not `reqHeaders`.
Note that this was a regression in v9.0.0; the [equivalent line before the refactor](https://github.com/npm/make-fetch-happen/blob/4f3384738fe02a993b0e9f94f182ea5831975bf7/index.js#L41) grabbed `this` and called that …
> fix: make `defaults` chaining actually work (v9 regression)

- README.md
- lib/cache/entry.js
- lib/remote.js
- package.json
- test/cache.js
- test/cacheable-response-invalid-integrity.js
- test/events.js
this makes it so we share our own integrity stream with cacache, so we avoid double hashing.
~this builds on #150, land that first~ #150 broke tests, but the feature of deduplicating the integrity stream fixed them, so might as well just land these together
> fix: pass integrityEmitter to cacache to avoid a redundant integrity stream

- lib/cache/entry.js
- lib/pipeline.js
- lib/remote.js
- test/pipeline.js
this caching is necessary because it's possible that the pipeline may start flowing data and these events may be emitted before we have a chance to setup listeners for them, so to be sure that our downstream consumers (like cacache) receive these events, we cache the data and re-emit them immediately when a new listener is added
> fix: cache integrity and size events so late listeners still get them

- lib/remote.js
- package.json
- test/cache.js
this corrects the issue where we write content with an expected sha1 integrity as sha512 causing us to effectively not cache it at all, now content is correctly written as sha1 and can be read from the cache appropriately
> fix: respect given algorithms instead of always using sha512

- lib/agent.js
- test/agent.js
In the documentation and code of `socks-proxy-agent` 7.0.0, the `SocksProxyAgent` class is no longer exported by default.
So when we use the default export, the error `SocksProxyAgent is not a constructor` will be thrown
> fix: TypeError: SocksProxyAgent is not a constructor

- lib/cache/entry.js
This PR just adds the response link header to the cached information. This header contains data we could store without compromising security or affecting the cache.
I need this header because I'm caching responses from the GitHub API and without this header, I cannot paginate the responses.
I have tested it and is working and the tests are passing.
related to #62 #64
> feat: Store the link header in cache

- README.md
`onRetry` is always called with one of the following:
1. A response from minipass-fetch
https://github.com/npm/make-fetch-happen/blob/2631db8306864f1812278d560b9bd0ca400478cd/lib/remote.js#L83
2. An error thrown by or from a rejected promise from minipass-fetch or promise-retry
https://github.com/npm/make-fetch-happen/blob/2631db8306864f1812278d560b9bd0ca400478cd/lib/remote.js#L106
This PR updates the documentation to reflect this.
I have not added an entry to the changelog as it is not requested in the contribution guide and I don't believe that this change merits one.
> docs(readme): Document cause argument to onRetry

- README.md
- lib/cache/entry.js
- lib/options.js
- test/cache.js
- test/options.js
supersedes #64
closes #62 
credit belongs to @tompahoward as this was based on their idea.
> feat: add support for caching additional headers

- lib/remote.js
- package.json
- test/cache.js
- test/fetch.js
- test/options.js
Three commits:
- **deps: add proc-log@4.2.0**
- **fix: log errors on retry**
- **chore: fix linting in test files**
Closes https://github.com/npm/cli/issues/7371
> Log retries

- package.json
This dependency stopped being used in commit 7c25367, as the responsibility for the HTTP agent was moved outside this package, but the dependency was not removed from package.json.
`@npmcli/agent` doesn't use `is-lambda` either, so this does actually remove a dependency.
> deps: remove is-lambda dependency

- lib/remote.js
Following an upgrade from `13.0.1` to `14.0.1` (which included upgrading `@npmcli/agent` from `2.0.0` to `3.0.0`), we've seen strange behaviour: a request works the first time, then immediately times out after that.
We're setting a `signal` on each request, which due to changes in `@npmcli/agent` is then also used by the agent for connections. The problem is that the original signal is used for all requests due to agent caching. Once it's been used (i.e. after the first time a request is made), no connections are possible (as they're immediately rejected). This change resolves our issue by removing the signal from the agent.
I looked into adding a test, but I don't think it's possible without making real network requests.
> fix: don't use the request signal in the agent

- lib/options.js
- test/options.js
Currently NODE_TLS_REJECT_UNAUTHORIZED is simply ignored as options.rejectUnauthorized is always set to false when strictSSL is not defined.
Most notably this causes issues for users behind corporate proxies using npm and pnpm when installing a package that uses node-gyp. Example: https://github.com/nodejs/node-gyp/issues/2663
This change only takes into account NODE_TLS_REJECT_UNAUTHORIZED when strictSSL is not passed to fetch.
unit tests were added to ensure strictSSL is still the primary driver.
> fix: stop ignoring NODE_TLS_REJECT_UNAUTHORIZED when strictSSL is not defined
